// export * from './auth/auth.services'
export { dishes_services } from './dish.services'
export { default as categories_services } from './category.services'
export { orders_services } from './order.services'
export { auth_services } from './auth.services'
export { user_services } from './user.services'