import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Pacifico, Varela_Round } from "next/font/google";
import { Footer, Header } from "@/components/app";
import { StoreProvider, SWRProvider } from "@/components";

const varelaRound = Varela_Round({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-varela-round",
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
});

const nunito = Nunito({
  weight: ["600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-nunito",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Foodie Restaurant",
  description: "Generated by create next app",
};


function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className="scroll-smooth" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} 
        ${varelaRound.variable} ${nunito.variable} antialiased`}
      >
        <SWRProvider>
          <StoreProvider>
            {children}
          </StoreProvider>
        </SWRProvider>
      </body>
    </html>
  );
}

export { metadata };
export default RootLayout;